### PR TITLE
define MemberState

### LINKED ISSUE #38: [suspicion] member state
MemberState is used to manage our state view of another member.
I think MemberState should include:
* member info
* status
* incarnation number
* timestamp

### PR DESCRIPTION
**Pull request by zeroFruit**
resolved: #38 

details:

define `MemberState` to help to keep and manage states of other members in network

### CODE REVIEW

**Comment by junbeomlee** [comment]
I think member state should be in member. So how about this
```
type Member struct{
        // ip address
	Addr net.IP

	// port
	Port uint16

	// status: Unknown, alive, suspected, dead
	Status Status

	Incarnation uint32

 	// Time last status change happened
	StatusChange time.Time

}
```

**Comment by zeroFruit** [comment]
@junbeomlee 
I think your idea is much better that member has states! then how about abstract state like this

```go
type Member struct{
        // ip address
	Addr net.IP

	// port
	Port uint16

        // abstract member state
        State MemberState
}
```

**Comment by hihiboss** [comment]
I think @junbeomlee 's is better than @zeroFruit 's because `MemberState` would have weak meaning. If `MemberState` has just State and ChangeTime, it might be going to be more complicated...? I think..so...

**Comment by zeroFruit** [comment]
Ok I would follow that! 👍

**Comment by junbeomlee** [comment]
how about changing `Status` to `status Status`

**Comment by zeroFruit** [comment]
good! I would also change incarnation to private!

**Review by junbeomlee — APPROVED** [review]

**Pull request merged**
