### PR TITLE
Move docs to README.md

### PR DESCRIPTION
**Pull request by junbeomlee**

### CODE REVIEW

**Comment by hihiboss** [comment]
Is it too long to use for README??

**Comment by junbeomlee** [comment]
It would be nice to tell me which part to reduce.

**Comment by hihiboss** [comment]
After merging this PR, I'll polish it. I think that a part to be implemented is better than all SWIM explanation. Also, I think it could be reduced as merging `Suspicion mechanism` and `How Suspicion Protocol Works`.

**Comment by junbeomlee** [comment]
okay plz approve this

**Pull request merged**
