### PR TITLE
fix: dependency it-chain to de-labtory

### LINKED ISSUE #120: [swim] change dependency it-chain to de-labtory
swim project use it-chain/heimdall & it-chain/ilogger

it must be changed to de-labtory

### PR DESCRIPTION
**Pull request by hea9549**
resolved: #120 

details:
- fix it-chain/heimdall to de-labtory/heimdall
- fix it-chain/ilogger to de-labtory/heimdall
- fix dependency it-chain to de-labtory in go.mod

- [x] Test case

### CODE REVIEW

**Comment by hea9549** [comment]
@zeroFruit plz review to merge this PR :)

**Review by hihiboss — APPROVED** [review]
Nice work!

**Comment by AgwaB** [comment]
gooood

**Comment by hea9549** [comment]
if anymore review until tomorrow, i'll merge this PR ! :)

**Pull request merged**
